language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino
  - PLATFORMIO_PROJECT_DIR=examples/native
  - PLATFORMIO_PROJECT_DIR=examples/simba

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email:
    recipients:
      - tang@qitas.cn
    on_success: never   # default: change
    on_failure: always  # default: always
