name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
      # - "[0-9]+.[0-9]+.[0-9]+*"

env:
  UPLOAD_BUILD: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        example:
          - "arduino-blink"
          - "arduino-wifiscan"
          - "simba-blink"
          - "arduino-asyncudp"
          - "arduino-webserver"
          - "esp8266-nonos-sdk-blink"
          - "esp8266-rtos-sdk-blink"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install file://.

      - name: Build
        working-directory: examples
        run: |
          qio run -d ${{ matrix.example }}

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: qio_${{ matrix.example }}_${{ matrix.os }}
          path: examples/${{ matrix.example }}/.pio

  build_fail:
    needs:
      - build
    if: failure() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}/${GITHUB_REF/refs\/tags\//}
          message: "build fail"

      - name: Delet tag
        run: |
          git fetch
          git tag -d ${GITHUB_REF/refs\/tags\//}
          git push origin :refs/tags/${GITHUB_REF/refs\/tags\//}

  templete:
    needs:
      - build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        template:
          - "A"
          - "B"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install file://.

      - name: Checkout templete
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T51${{ matrix.template }}
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: ${{ matrix.template }}

      - name: Build templete
        if: success()
        working-directory: ${{ matrix.template }}
        run: |
          qio run -d .

  release:
    needs:
      - templete
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Generate tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'OS-Q/P51'
        run: |
          echo "::set-output name=release_tag::release_$(date +"%Y.%m.%d")_${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=status::success"

      - name: Package
        id: package
        run: |
          echo "Platform P51 for ESP8266 WiFi SoC" >> log.txt
          echo $(date +"%Y.%m.%d") >> log.txt
          echo ${GITHUB_REF/refs\/tags\//} >> log.txt
          echo "www.OS-Q.com\n" >> log.txt
          git log --stat -1 >> log.txt
          echo ${GITHUB_REF/refs\/tags\//} >> qio/mail.md
          echo $(date +"%Y.%m.%d") >> qio/mail.md
          mkdir sources
          cp -rf boards builder extend monitor link.json link.py platform.json platform.py sources
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload Firmware
        if: steps.package.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v2
        with:
          name:  P51_${{ steps.tag.outputs.release_tag }}
          path: sources/

      - name: Upload Release
        id: upload-release
        uses: Qful/release-action@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        with:
          tag_name: ${GITHUB_REF/refs\/tags\//}
          files: |
            ${{ env.FIRMWARE }}/package.zip
            ${{ env.FIRMWARE }}/log.txt

  release_fail:
    needs:
      - release
    if: failure() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}/${GITHUB_REF/refs\/tags\//}
          message: "release fail"

      - name: Delet tag
        run: |
          git fetch
          git tag -d ${GITHUB_REF/refs\/tags\//}
          git push origin :refs/tags/${GITHUB_REF/refs\/tags\//}

  release_oss:
    needs:
      - release
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}/${GITHUB_REF/refs\/tags\//}
          message: "release success"

      - name: Folder
        id: folder
        run: |
          zip -r package.zip boards builder extend monitor link.json link.py platform.json platform.py
          # mkdir sources
          # cp -rf boards builder extend monitor link.json link.py platform.json platform.py sources
          echo "::set-output name=status::success"

      - name: Setup OSS
        uses: Qful/ossutil-action@master
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Upload OSS
        id: OSS
        run: |
          cp package.zip P51.zip
          cp package.zip P51_${GITHUB_REF/refs\/tags\//}.zip
          ossutil cp ${{ env.FIRMWARE }}/P51.zip ${{ secrets.OSS_P_BUCKET }} -rf
          ossutil cp ${{ env.FIRMWARE }}/P51_${GITHUB_REF/refs\/tags\//}.zip ${{ secrets.OSS_P_BUCKET }} -f
          echo "::set-output name=status::success"

      # - name: Delet tag
      #   run: |
      #     git fetch
      #     git tag -d ${GITHUB_REF/refs\/tags\//}
      #     git push origin :refs/tags/${GITHUB_REF/refs\/tags\//}

  release_templete:
    needs:
      - release_oss
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Checkout templete
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T51A
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: A

      - name: Checkout templete
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T51B
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: B

      - name: Checkout boards
        uses: actions/checkout@v2
        with:
          repository: OS-Q/B51
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: board

      - name: Folder
        id: folder
        run: |
          mv -f board boards
          rm -rf examples
          mkdir examples
          cp -rf A B examples
          zip -r package.zip examples boards builder extend monitor link.json link.py platform.json platform.py
          echo "::set-output name=status::success"

      - name: Setup OSS
        uses: Qful/ossutil-action@master
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Upload OSS
        id: OSS
        run: |
          cp package.zip P51T.zip
          cp package.zip P51T_${GITHUB_REF/refs\/tags\//}.zip
          ossutil cp ${{ env.FIRMWARE }}/P51T.zip ${{ secrets.OSS_P_BUCKET }} -rf
          ossutil cp ${{ env.FIRMWARE }}/P51T_${GITHUB_REF/refs\/tags\//}.zip ${{ secrets.OSS_P_BUCKET }} -f
          echo "::set-output name=status::success"

      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}/${GITHUB_REF/refs\/tags\//}
          message: "release templete success"

  rebuild:
    needs:
      - release
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        id: getgh
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install https://github.com/OS-Q/P51/releases/latest/download/package.zip
          echo "::set-output name=status::success"

      - name: ReBuild
        id: rebuild
        if: steps.getgh.outputs.status == 'success' && !cancelled()
        run: |
          qio run -d examples/arduino-blink
          qio run -d examples/simba-blink
          echo "::set-output name=status::success"

      - name: Send Mail
        if: steps.rebuild.outputs.status == 'success' && !cancelled()
        uses: Qful/mail-action@master
        with:
          server_address:  smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: OS-Q P51 package released (ESP8266)
          to: ${{secrets.MAIL_TO}}
          from: Qitas
          cc: ${{github.event.pusher.email}}
          content_type: text/html
          convert_markdown: true
          attachments: log.txt
          body: file://./qio/mail.md

  rebuild_pass:
    needs:
      - rebuild
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "rebuild success"


  rebuild_fail:
    needs:
      - rebuild
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "rebuild fail"
