name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build:
    if: github.repository == 'OS-Q/P51'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
        package:
          - "release"
          - "latest"
        examples:
          - "examples/arduino"
          - "examples/native"
          - "examples/simba"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install release
        if: matrix.package == 'release'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P51/releases/latest/download/P51.zip

      - name: Install latest
        if: matrix.package == 'latest'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        id: build
        if: success()
        run: |
          pio run -d ${{ matrix.examples }}
          echo "::set-output name=status::success"

  update:
    needs:
      - build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: OS-Q/P51E
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: OSQ

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git config --global user.email "qitas@qitas.cn"
          git config --global user.name "qitas"

      - name: commit
        working-directory: OSQ
        run: |
          git pull
          cp -rf ../boards .
          cp -rf ../builder .
          cp -rf ../extend .
          cp -f ../link.json .
          cp -f ../link.py .
          git add .
          git commit -am "update by github action"
          git push
          echo "::set-output name=status::success"
