name: nightly

# on:
#   schedule:
#     - cron: "0 8 * * *"
on:
  push:
    branches:
      - master
      - main

env:
  UPLOAD_BUILD: false

jobs:
  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "simba-blink"
          - "arduino-blink"
          - "arduino-wifiscan"
          - "arduino-asyncudp"
          - "arduino-webserver"
          - "esp8266-nonos-sdk-blink"
          - "esp8266-rtos-sdk-blink"

        os: [ubuntu-latest, windows-latest, macos-latest]
        package:
          - "all"
          - "lite"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install all
        if: matrix.package == 'all'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          pio platform install https://github.com/OS-Q/P51/releases/latest/download/package.zip

      - name: Install lite
        if: matrix.package == 'lite'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install https://github.com/OS-Q/P51/releases/latest/download/sources.zip

      - name: Build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: qio_build_${{ matrix.example }}_${{ matrix.package }}
          path: examples/${{ matrix.example }}/.pio/build/

  QIO_fail:
    needs:
      - QIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO build failure"

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "simba-blink"
          - "arduino-blink"
          - "arduino-wifiscan"
          - "arduino-asyncudp"
          - "arduino-webserver"
          - "esp8266-nonos-sdk-blink"
          - "esp8266-rtos-sdk-blink"

        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9


      - name: Install dependencies
        working-directory: PIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P51/releases/latest/download/package.zip

      - name: Build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: pio_build_${{ matrix.example }}
          path: examples/${{ matrix.example }}/.pio/build/

  PIO_fail:
    needs:
      - PIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "PIO build failure"
